### ISSUE TITLE
这么久都没人么

### ISSUE THREAD

**Issue by liweichen6** [SplashCodes/JAViewer#1]
那我就来吐个槽吧
看了下信息都是从MOO那边抓的
于是和网页对比了下
首先题图不能点开，这个说实话还不算重要
最蛋疼的是加载速度实在慢的诡异
网页轻松跑个几m的时候app只能到20k

**Comment by SplashCodes** [comment]
网页会同时加载全部图片所以流量比较大。速度这锅得丢给GFW。
