### ISSUE TITLE
app崩溃

### ISSUE THREAD

**Issue by wxydhr123** [SplashCodes/JAViewer#107]
我从12.09的影片拉倒11.24之后，再点击进去，APP就崩溃了，能不能建立分页或者添加跳转栏，：不然每次都得一直往下拉，时间跨度大的话很麻烦。

**Comment by 1357209470** [comment]
avmoo也是变烂了，有些番号不显示发行日期，久远的的番号网页直接404网页错误了，一直也都没修复。希望作者大大能把软件改成翻页模式，上下滑动真不太方便，一退出就要重新来过，好几次遇到源站网页错误然后软件崩溃翻了半天的番号又要重新来过，真是砸了手机的心都有了。希望大大能把改成翻页模式，这样就能记住上次看到哪了。

**Comment by 1357209470** [comment]
avmoo真不太好使了像一些番号都不在同番号系列中展示了，只有搜索具体番号才能出来。可以的希望作者大大能再加个源

**Comment by Ccixyj** [comment]
@1357209470 @wxydhr123  推荐一下https://github.com/Ccixyj/JBusDriver
