### ISSUE TITLE
能不能把收藏夹等列表里搜索图标恢复了

### ISSUE THREAD

**Issue by Climamba** [SplashCodes/JAViewer#108]
以前在收藏夹里也能搜索 现在翻收藏夹时想搜索只能退回主页再搜索 搜索完还得再手动翻回刚才看到的地方 好麻烦

**Comment by SplashCodes** [comment]
暂时不考虑，因为收藏夹加搜索图标更倾向于暗示用户搜索收藏夹里的内容，这个和目前功能是不符的，所以移除了。。
