### ISSUE TITLE
收藏的功能

### ISSUE THREAD

**Issue by Pradesid** [SplashCodes/JAViewer#12]
希望能增加云盘备份 就是可以打包收藏夹里的链接然后备份邮箱里或者云盘里 自己的云盘也行。用分享功能就好。还有希望能在收藏里能增加排序功能，自己可以加本地tag这样，可以根据tag排序分类，二级目录功能 可以在收藏里分类某个演员的影片都在一个演员头像下。

**Comment by YiFunC** [comment]
云备份就要服务器，有点难

**Comment by tsubasa-kun** [comment]
云备份就不用了，可以导出到本地文件就可以，txt，word之类的文本。
