### ISSUE TITLE
安卓7.0编译版本（非作者发布）

### ISSUE THREAD

**Issue by q310550690** [SplashCodes/JAViewer#14]
作者编译的1.2版本7.0下会闪退，所以下了作者源码重新编译了一个，完美运行

百度云地址：http删://pan.baidu.com删/s/1dEAVWHz    密钥：k1dr

**Comment by skysumbra** [comment]
再補一下運行版本是多少至7.0系統，或許比較好，方便觀察

**Comment by q310550690** [comment]
这个没有注意看，是直接下载了你前几天上传的源码直接编译的。

**Comment by skysumbra** [comment]
to q310550690
你現在還有在編寫或是練習Android?
我可以問你問題嗎？像是用qq之類問你

**Comment by q310550690** [comment]
@skysumbra 我不会安卓

**Comment by 1357209470** [comment]
谢谢楼主真的太感谢了 都快憋死了 幸好看见了楼主的帖子 谢谢楼主
