### ISSUE TITLE
jav图书馆的configurations.json文件复制到javiwer的目录下收藏的女优无法显示

### ISSUE THREAD

**Issue by fsy953643268** [SplashCodes/JAViewer#142]
如题，收藏的影片是可以正常显示的，希望两者可以兼容。它用的也是你的源码，可能这个收藏用的是以前的模式吧，已经年久失修了～另外作者可以考虑向图书馆的功能发展标签和源都挺有用的呢，谢谢作者大大啦～

**Comment by fsy953643268** [comment]
希望作者大大可以看到

**Comment by Torahlzy** [comment]
@fsy953643268 老哥，jav图书馆项目地址是哪个

**Comment by fsy953643268** [comment]
@Torahlzy，QQ⑨⑤③⑥④③②⑥⑧找我要
