### ISSUE TITLE
1.3.5最新版打不开任何内容，翻墙也打不开了

### ISSUE THREAD

**Issue by ZandEandV** [SplashCodes/JAViewer#143]

**Comment by zhdlod** [comment]
求大神传授方法或者发布更新，同打不开

**Comment by angelmengg** [comment]
同打不开

**Comment by magicaaaa** [comment]
+1

**Comment by magicaaaa** [comment]
以前出现过这种没有？

**Comment by cfx1995** [comment]
这次切换到1.3.2版本都没用了

**Comment by zhdlod** [comment]
没有，我下载时间不长，用了不到两个月，一直不需要翻墙，现在翻墙也打不开了，流量和WIFI环境下都是。只有收藏夹还能够看，但是收藏夹里面的内容也打不开

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: magicaaaa <notifications@github.com>
发送时间: Tuesday, June 26, 2018 1:20:40 PM
收件人: SplashCodes/JAViewer
抄送: zhdlod; Manual
主题: Re: [SplashCodes/JAViewer] 1.3.5最新版打不开任何内容，翻墙也打不开了 (#143)


以前出现过这种没有？

―

**Comment by magicaaaa** [comment]
凉了呀

**Comment by zhdlod** [comment]
别啊，这么好用的东西，翻车了怎么玩

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: magicaaaa <notifications@github.com>
发送时间: Tuesday, June 26, 2018 4:33:35 PM
收件人: SplashCodes/JAViewer
抄送: zhdlod; Manual
主题: Re: [SplashCodes/JAViewer] 1.3.5最新版打不开任何内容，翻墙也打不开了 (#143)


凉了呀

―

**Comment by angelmengg** [comment]
估计是网址换了，谁进去项目替换下最新的网址应该就可以

**Comment by magicaaaa** [comment]
要是会就不会在这问了...

**Comment by zhdlod** [comment]
别说会了，都不知道用的那个网址

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: magicaaaa <notifications@github.com>
发送时间: Tuesday, June 26, 2018 4:43:40 PM
收件人: SplashCodes/JAViewer
抄送: zhdlod; Manual
主题: Re: [SplashCodes/JAViewer] 1.3.5最新版打不开任何内容，翻墙也打不开了 (#143)


要是会就不会在这问了...

―

**Comment by SHY1226** [comment]
配置文件就在根目录，关键是连个能用的网页都找不到拿什么替换

**Comment by ZandEandV** [comment]
刚才翻墙，又连上了…

**Comment by magicaaaa** [comment]
大半夜的节制一点。。

**Comment by itabxt** [comment]
经测试，只有欧美源有问题，源站出了问题。

**Comment by JJayce** [comment]
新网址是https完  javzoo 美 com

**Comment by wunai1234** [comment]
我想问一下作者还活着吗。。。
