### ISSUE TITLE
无码板块失效

### ISSUE THREAD

**Issue by XDXT** [SplashCodes/JAViewer#147]
无码板块已经失效，楼主啥时候打包更新啊

**Comment by hjp070928** [comment]
我看到文件一直在更新，在哪能下到最新版本0

**Comment by XDXT** [comment]
直接看作者源代码，你会就自己打包成app呗

**Comment by kincaid168** [comment]
不会打包

**Comment by SplashCodes** [comment]
https://github.com/SplashCodes/JAViewer/commit/7ef3ad41b72d738f18cfe3161e5bb569d80901a2
