### ISSUE TITLE
希望可以加入里番啊

### ISSUE THREAD

**Issue by leeang104** [SplashCodes/JAViewer#15]
就是h动漫
而且我看更新那里，都出一月二十八号的片子了，这是时差？

**Comment by leeang104** [comment]
仅仅只是希望，您们现在做的也很好！

**Comment by SplashCodes** [comment]
没有数据源呢 :(

**Comment by InvalidNames** [comment]
@SplashCodes 电脑上又个软件叫轻轻一点（qqyddm.com），里面有里番的数据，大神可以抓一下他的数据源，不过软件好像有毒

**Comment by ezio123456** [comment]
同求里番   希望加入按番号分类  比如ipz  wanz

**Comment by CrabAss** [comment]
琉璃神社？

**Comment by SplashCodes** [comment]
琉璃神社有自己的app :/

**Comment by Vstory** [comment]
里番+1

**Comment by gjhjjfgjg** [comment]
直接抓字幕组的放流，可惜ny倒下了，不然就可以直接抓ny(国外放流站)

**Comment by baiyiin** [comment]
可以加入观看功能就好了

**Comment by SnowRain1326** [comment]
其实只要加入调用神奇磁力就可以了吧
