### ISSUE TITLE
新版本多晚发布啊

### ISSUE THREAD

**Issue by Augn** [SplashCodes/JAViewer#150]
新版本多晚发布啊

**Comment by jonyjjoe** [comment]
请问如何下载软件？

**Comment by tcgsmo** [comment]
主页找releases，下载就行了

**Comment by tcgsmo** [comment]
然后同问啥时候更新- ̗̀(๑ᵔ⌔ᵔ๑)

**Comment by jonyjjoe** [comment]
楼上的谢谢啦，只是我始终找不到releases,里面都是代码，还有这个软件需要vpn吗，我以前都是直接下载的，现在网站好像变了

**Comment by kincaid168** [comment]
下载地址:https://github.com/SplashCodes/JAViewer/releases

**Comment by SplashCodes** [comment]
加了太多重磅功能，还有一些小问题优化，近期会马上发布大新闻。

**Comment by BigbombD** [comment]
最后像1.33一样能直接跳转到115上面，还有多加点网站源

**Comment by sex-squirrel** [comment]
在线观看是个牛逼的地方，片源多加一些更好，奈何只有一个

**Comment by mojans** [comment]
都两周了还没更新，没有欧美源要气死了

**Comment by xporn** [comment]
可以看看这个https://github.com/xporn/Xpiler

**Comment by xporn** [comment]
@mojans

**Comment by wunai1234** [comment]
还木有更新55555
