### ISSUE TITLE
1.3.5显示不出内容

### ISSUE THREAD

**Issue by yhlzkd** [SplashCodes/JAViewer#159]
应该是源网址换了，把json文件里的网址改成javzoo就成了，望更新修复

**Comment by magicaaaa** [comment]
改安装文件夹里面的那个.json？改了只能用一次，再打开就又GG了

**Comment by yhlzkd** [comment]
> 改安装文件夹里面的那个.json？改了只能用一次，再打开就又GG了

每次打开的时候不点切换源就行了

**Comment by hdbcjr** [comment]
手机上怎么修改啊

**Comment by all4real** [comment]
手机上可以修改么？

**Comment by gyhgyhgyj** [comment]
什么时候能好啊
