### ISSUE TITLE
解决1.3.5空白页的方法 

### ISSUE THREAD

**Issue by Guiawoa** [SplashCodes/JAViewer#160]
说明一下！ 我不是开发者！  我只是一个把解决问题的步骤记录下来 然后分享出来的人
只适用于有码！！！用es文件浏览器进手机主目录(sd卡目录）下的javiewer的文件夹然后打开里面configurations.json这个文件 用文字格式打开  接着用es文字编辑器   点一下编辑按钮  找到第六行（第一个大括号末尾处）  将https://javmoo.com改为https://avmoo.pw 点储存 退出  进软件时点 否  就正常了  有问题 找我企鹅（Guiawoa）或者贴吧（鬼啊我啊）  贴吧记得把陌生人信息打开 不然我回复你也看不到

**Comment by Guiawoa** [comment]
贴吧不是这个id 是中文：鬼啊我啊

**Comment by wutangningmeng** [comment]
请问是哪个文件夹呢

**Comment by Guiawoa** [comment]
网址又改了  现在是 avmoo.com

**Comment by wunai1234** [comment]
大佬求问是那一个文件夹啊

**Comment by wunai1234** [comment]
> 网址又改了 现在是 avmoo.pw

跪求老哥 到底是哪里 我单开了都是代码 找不到https://javmoo.com

**Comment by wunai1234** [comment]
谢谢大佬我会了！

**Comment by wutangningmeng** [comment]
楼上的那位，请问具体怎么操作才可以呢

**Comment by cdl521** [comment]
方法完全无用

**Comment by Guiawoa** [comment]
> 
> 
> 大佬求问是那一个文件夹啊

手机主目录下 ”JAViewer“文件夹

**Comment by Guiawoa** [comment]
> 
> 
> > 网址又改了 现在是 avmoo.pw
> 
> 跪求老哥 到底是哪里 我单开了都是代码 找不到https://javmoo.com
仔细找 就在第一个大括号里

**Comment by Guiawoa** [comment]
> 
> 
> > 网址又改了 现在是 avmoo.pw
> 
> 跪求老哥 到底是哪里 我单开了都是代码 找不到https://javmoo.com

现在网址是avmoo.pw  我也改进了一下教程

**Comment by Guiawoa** [comment]
> 
> 
> 方法完全无用

现在网址是avmoo.pw  我也改进了一下教程

**Comment by liangxiaoshi** [comment]
成功上车

**Comment by liangxiaoshi** [comment]
应该是旧网址被封或者墙了

**Comment by Karasu953** [comment]
我把应用卸载重装删除文件之后，没办法生成JAViewer文件夹下的文件了，有人可以告诉我文件的格式是什么吗

**Comment by wunai1234** [comment]
大佬改过后老是卡加载半天不显示 开vpn也一样  很不稳定 而且翻找资源翻到17年4 5月发布的资源时就直接崩溃了

**Comment by wunai1234** [comment]
> 楼上的那位，请问具体怎么操作才可以呢

手机文件夹直接搜javiewer 点开文件夹里面那个就是

**Comment by zhc12345** [comment]
大佬是不还有个app叫纸魅？ @Guiawoa 真棒！！！

**Comment by Guiawoa** [comment]
> 
> 
> 有效！感谢～但是每次打开都提示换源有点烦
这个还要靠原作者解决

**Comment by Guiawoa** [comment]
> 
> 
> 大佬是不还有个app叫纸魅？ @Guiawoa 真棒！！！

抱歉 我不是这软件的作者

**Comment by Guiawoa** [comment]
> 
> 
> 我把应用卸载重装删除文件之后，没办法生成JAViewer文件夹下的文件了，有人可以告诉我文件的格式是什么吗

进换成无码 然后再换回来 文件就生成了

**Comment by Forbuger** [comment]
还是等原作者解决吧，否则每次换源太麻烦了

**Comment by zzx00zzx** [comment]
大佬，试过了，还是不行

**Comment by ShmilyChen** [comment]
作者在软件中使用的源更新方式是请求这个git仓库的properties.json文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
可以自己动手在安装包的dex文件中搜索properties.json，然后将搜索出来的
https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json
改成自己的仓库文件地址就好
`https://raw.githubusercontent.com/你的git用户名/你的git仓库/分支/文件名`
无码源目测可以在
`https://tellme.pw/avsox`这个地址中找
附赠一份配置文件，我配置好了两个源的新地址可供参考使用
{ "latest_version": "2.0.0 Alpha 1", "latest_version_code": "13", "changelog": "**测试版更新**\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题", "data_sources": [ { "name": "AVMOO 日本", "link": "https://javzoo.com", "legacies":[ "avmoo.net", "avmoo.pw", "javmoo.com", "javlog.com", "javtag.com", "javhip.com", "avos.pw", "avmo.pw", "avmo.club", "avio.pw", "javdog.com", "javmoo.net" ] }, { "name": "AVMOO 日本无码", "link": "https://avme.pw", "legacies":[ "javkey.com", "javfee.com", "javpee.com", "avso.pw", "avso.club" ] } ] }
