### ISSUE TITLE
无码源站：https://avsox.net/  

### ISSUE THREAD

**Issue by Guiawoa** [SplashCodes/JAViewer#161]
有条件的可以自己改试试

**Comment by magicaaaa** [comment]
怎么改啊？json文件里没看到有无码的链接可以替换的。

**Comment by nhnjde** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
倌伪俑净嘲觅磁覆还诵岗稚谎掖吵钥
[ ](https://github.com/ifsird/ufdkl/)
[ ](https://github.com/ifxspo/igp/)
[ ](https://github.com/krazb2l/use5h/)
[ ](https://github.com/fghhgks/eridf/)
[ ](https://github.com/tlkxt/ifz/)
