### ISSUE TITLE
2.0版本体验

### ISSUE THREAD

**Issue by Chonglian233** [SplashCodes/JAViewer#173]
预览画质感觉是最差的画质了，没什么预览的价值，个人感觉可以取消，主要是因为在线播放也能达到预览的效果了，而且画质比预览的好，速度也快（个人觉得观看高清及以上画质还是下载下来的好），其他问题以后慢慢体验吧，有个建议是能选择其他网站来获取封面及预览图片和链接，从而避免当前网站失效的情况（技术方面不知道麻烦不麻烦），再问下收藏有没有上限，能不能添加一个忽略功能来忽略掉自己不想看的某标签类的或某部片子的功能，最后感谢作者大大的分享

**Comment by xf1998201** [comment]
怎么下载的呀 朋友 我的一直下载不了

**Comment by 1535128201** [comment]
想问一下，压缩包里没有apk文件该如何安装？拉一个原来的apk进去吗？

**Comment by xf1998201** [comment]
> 想问一下，压缩包里没有apk文件该如何安装？拉一个原来的apk进去吗？

不是直接在网页 里面下载apk吗  但是那个好像是国外的 必须翻墙才能下载

**Comment by SplashCodes** [comment]
好的，预览功能的确没什么用，可以移除。

**Comment by baddog001** [comment]
求教如何下载apk文件，网页只有压缩文件

**Comment by slender09** [comment]
在Releases里面



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
由： baddog001 <notifications@github.com>
日期: 2018/12/6 02:43 (GMT+08:00)
收件人： SplashCodes/JAViewer <JAViewer@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： Re: [SplashCodes/JAViewer] 2.0版本体验 (#173)


求教如何下载apk文件，网页只有压缩文件

―

**Comment by hbfxlx** [comment]
可以下载，

**Comment by PLQin** [comment]
https://github.com/SplashCodes/JAViewer/releases

不用谢, 好人一生平安
