### ISSUE TITLE
关于在线播放地址解析

### ISSUE THREAD

**Issue by 670848654** [SplashCodes/JAViewer#197]
![1](https://user-images.githubusercontent.com/18481749/49630297-831aaf00-fa28-11e8-837c-4a5a80206419.png)
请教一下这个Api是怎么找到的，我在项目中使用了您这部分代码

**Comment by MagicDroidX** [comment]
这个api是我们自己的…不是外面找的

**Comment by SplashCodes** [comment]
这个api是我自己搭建的，没有打算公开使用，望理解！

**Comment by 670848654** [comment]
我已经关闭了项目,谢谢

> 这个api是我自己搭建的，没有打算公开使用，望理解！
