### ISSUE TITLE
能不能添加多一个视频网站地址

### ISSUE THREAD

**Issue by lendless** [SplashCodes/JAViewer#219]
地址链接：https://www5.javmost.com

**Comment by adrhe** [comment]
https://avgle.com不错啊

**Comment by lendless** [comment]
但是avgle有些片没资源😁-------- 原始邮件 --------主题：Re: [SplashCodes/JAViewer] 能不能添加多一个视频网站地址 (#219)发件人：Chuan 收件人：SplashCodes/JAViewer 抄送：lendless ,Author https://avgle.com不错啊

**Comment by kincaid168** [comment]
你说的这个https://www5.javmost.com/网站，都是直接调用的avgle的视频源。
