### ISSUE TITLE
最新版1.2.1卡在启动画面

### ISSUE THREAD

**Issue by Fly12345** [SplashCodes/JAViewer#23]
最新版1.2.1卡在启动画面，等了十几秒闪退到桌面，旧的1.2.0就可以进入。望大神能修复一下，感谢！

用的是红米note2  系统是MIUI7

**Comment by MagicDroidX** [comment]
需要 logcat

**Comment by SplashCodes** [comment]
请提供报错内容，谢谢。因为我这里没有收到任何报错不知道怎么修复。

**Comment by SplashCodes** [comment]
请试试1.2.2
