### ISSUE TITLE
牛头不对马嘴！

### ISSUE THREAD

**Issue by 15249765791** [SplashCodes/JAViewer#241]
播放资源错乱，实际在线播放的AV与标题AV不同，望尽快修复。

**Comment by nujnay** [comment]
不是 你白嫖还用这个语气

**Comment by 15249765791** [comment]
抱歉😜


发自139邮箱

**Comment by HelloWangXiangDong** [comment]
应该是根据标识符搜索资源的时候，搜到了超过1个以上的资源，自动播放了第一个。。
建议在播放界面加入列表功能，把符合条件的都列出来。。。

**Comment by erenlsy** [comment]
确实是这个毛病，播了几个发现一个对的都没有

**Comment by 15249765791** [comment]
才知道啊😃




发自139邮箱

**Comment by WayneY** [comment]
> 应该是根据标识符搜索资源的时候，搜到了超过1个以上的资源，自动播放了第一个。。
> 建议在播放界面加入列表功能，把符合条件的都列出来。。。

不要乱猜…… 是调用 rekonquer 的api 返回的内容就是错的，根本不是APP能解决的问题。除非换个api服务。

**Comment by 15249765791** [comment]
好的，大大。还能解决吗？

发自我的HM-I502-FL2019年3月6日 14:39 於 ivvei <notifications@github.com> 寫道：
