### ISSUE TITLE
给个链接大家可以支持一下

### ISSUE THREAD

**Issue by AxlXNick** [SplashCodes/JAViewer#247]
顺便反馈BUG。
1.在线播放的视频基本上都是错的。
以及建议新开的功能
1.欧美区可以考虑加进来吗
2.多标签查询
3.多页面任务，就像浏览器多个网页互不干扰一样。两个都行。

**Comment by linqwelin** [comment]
这种事

**Comment by Forbuger** [comment]
好久没更新，作者没支持估计是不愿意做下去了吧

**Comment by Forbuger** [comment]
还是一如既往支持作者

**Comment by smallminmin** [comment]
想要IOS版...嘿嘿

**Comment by 1148877908** [comment]
我也想看欧美区

**Comment by lvzhishang** [comment]
以前是有欧美区，不过后来看不到缩略图了，再后来就没有了。。。
