### ISSUE TITLE
解决空白页尝试新域名javzoo.com

### ISSUE THREAD

**Issue by Dnchenceta** [SplashCodes/JAViewer#254]
参考了[Guiawoa](https://github.com/SplashCodes/JAViewer/issues/160)的方法：
域名改为 “https://javzoo.com” 即可。

**Comment by C7890** [comment]
你好具体在哪里改呢？我没有他说的那个文件

**Comment by ShmilyChen** [comment]
作者在软件中使用的源更新方式是请求这个git仓库的properties.json文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
可以自己动手在安装包的dex文件中搜索properties.json，然后将搜索出来的
`https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json`
改成自己的仓库文件地址就好
附赠一份配置文件
`{
  "latest_version": "2.0.0 Alpha 1",
  "latest_version_code": "13",
  "changelog": "**测试版更新**\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题",
  "data_sources": [
    {
      "name": "AVMOO 日本",
      "link": "https://javzoo.com",
      "legacies":[
        "avmoo.net",
        "avmoo.pw",
        "javmoo.com",
        "javlog.com",
        "javtag.com",
        "javhip.com",
        "avos.pw",
        "avmo.pw",
        "avmo.club",
        "avio.pw",
        "javdog.com",
        "javmoo.net"
      ]
    },
    {
      "name": "AVMOO 日本无码",
      "link": "https://avme.pw",
      "legacies":[
        "javkey.com",
        "javfee.com",
        "javpee.com",
        "avso.pw",
        "avso.club"
      ]
    }
  ]
}`

**Comment by ShmilyChen** [comment]
作者在软件中使用的源更新方式是请求这个git仓库的properties.json文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
可以自己动手在安装包的dex文件中搜索properties.json，然后将搜索出来的
https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json
改成自己的仓库文件地址就好
https://raw.githubusercontent.com/你的git用户名/你的git仓库/分支/文件名
无码源目测可以在
https://tellme.pw/avsox这个地址中找
附赠一份配置文件，我配置好了两个源的新地址可供参考使用
{ "latest_version": "2.0.0 Alpha 1", "latest_version_code": "13", "changelog": "测试版更新\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题", "data_sources": [ { "name": "AVMOO 日本", "link": "https://javzoo.com", "legacies":[ "avmoo.net", "avmoo.pw", "javmoo.com", "javlog.com", "javtag.com", "javhip.com", "avos.pw", "avmo.pw", "avmo.club", "avio.pw", "javdog.com", "javmoo.net" ] }, { "name": "AVMOO 日本无码", "link": "https://avme.pw", "legacies":[ "javkey.com", "javfee.com", "javpee.com", "avso.pw", "avso.club" ] } ] }

**Comment by ShmilyChen** [comment]
作者在软件中使用的源更新方式是请求这个git仓库的properties.json文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
可以自己动手在安装包的dex文件中搜索properties.json，然后将搜索出来的
https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json
改成自己的仓库文件地址就好
https://raw.githubusercontent.com/你的git用户名/你的git仓库/分支/文件名
无码源目测可以在
https://tellme.pw/avsox这个地址中找
附赠一份配置文件，我配置好了两个源的新地址可供参考使用
```
{ "latest_version": "2.0.0 Alpha 1", "latest_version_code": "13", "changelog": "测试版更新\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题", "data_sources": [ { "name": "AVMOO 日本", "link": "https://javzoo.com", "legacies":[ "avmoo.net", "avmoo.pw", "javmoo.com", "javlog.com", "javtag.com", "javhip.com", "avos.pw", "avmo.pw", "avmo.club", "avio.pw", "javdog.com", "javmoo.net" ] }, { "name": "AVMOO 日本无码", "link": "https://avme.pw", "legacies":[ "javkey.com", "javfee.com", "javpee.com", "avso.pw", "avso.club" ] } ] }
```

**Comment by wunai1234** [comment]
> 作者在软件中使用的源更新方式是请求这个git仓库的`properties.json`文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
> 可以自己动手在安装包的`dex`文件中搜索`properties.json`，然后将搜索出来的
> `https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json`
> 改成自己的仓库文件地址就好
> `https://raw.githubusercontent.com/你的git用户名/你的git仓库/分支/文件名`
> 无码源目测可以在`https://tellme.pw/avsox`这个地址中找
> 有码源目测可以在`https://tellme.pw/avmoo`这个地址中找
> 附赠一份配置文件，我配置好了两个源的新地址可供参考使用
> 
> ```
> {
>   "latest_version": "2.0.0 Alpha 1",
>   "latest_version_code": "13",
>   "changelog": "**测试版更新**\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题",
>   "data_sources": [
>     {
>       "name": "AVMOO 日本",
>       "link": "https://avmoo.xyz",
>       "legacies":[
>         "avmoo.net",
>         "avmoo.pw",
>         "javmoo.com",
>         "javlog.com",
>         "javtag.com",
>         "javhip.com",
>         "avos.pw",
>         "avmo.pw",
>         "avmo.club",
>         "avio.pw",
>         "javdog.com",
>         "javmoo.net"
>       ]
>     },
>     {
>       "name": "AVMOO 日本无码",
>       "link": "https://avsox.net",
>       "legacies":[
>         "javkey.com",
>         "javfee.com",
>         "javpee.com",
>         "avso.pw",
>         "avso.club"
>       ]
>     }
>   ]
> }
> ```

大佬 是直接在手机文件里面搜索吗

**Comment by ShmilyChen** [comment]
> > 作者在软件中使用的源更新方式是请求这个混帐的仓库`properties.json`文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
> > 可以自己动手在安装包的`dex`文件中搜索`properties.json`，将然后搜索出来的
> > `https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json`
> > 改成自己的仓库文件地址就好
> > `https://raw.githubusercontent.com/你的git用户名/你的git仓库/分支/文件名`
> > 无码源目测可以在`https://tellme.pw/avsox`这个地址中找
> > 有码源目测可以在`https://tellme.pw/avmoo`这个地址中找
> > 附赠一份配置文件，我配置好了两个源的新地址可供参考使用
> > ```
> > {
> >   "latest_version": "2.0.0 Alpha 1",
> >   "latest_version_code": "13",
> >   "changelog": "**测试版更新**\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题",
> >   "data_sources": [
> >     {
> >       "name": "AVMOO 日本",
> >       "link": "https://avmoo.xyz",
> >       "legacies":[
> >         "avmoo.net",
> >         "avmoo.pw",
> >         "javmoo.com",
> >         "javlog.com",
> >         "javtag.com",
> >         "javhip.com",
> >         "avos.pw",
> >         "avmo.pw",
> >         "avmo.club",
> >         "avio.pw",
> >         "javdog.com",
> >         "javmoo.net"
> >       ]
> >     },
> >     {
> >       "name": "AVMOO 日本无码",
> >       "link": "https://avsox.net",
> >       "legacies":[
> >         "javkey.com",
> >         "javfee.com",
> >         "javpee.com",
> >         "avso.pw",
> >         "avso.club"
> >       ]
> >     }
> >   ]
> > }
> > ```
> 
> 大佬是直接在手机文件里面搜索吗
直接在apk里面的dex里面搜索啊（推荐使用mt2管理器）
把这个是我改好了的
[app-release(2)_sign.zip](https://github.com/SplashCodes/JAViewer/files/3124930/app-release.2._sign.zip)

**Comment by wunai1234** [comment]
> > > 作者在软件中使用的源更新方式是请求这个混帐的仓库`properties.json`文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
> > > 可以自己动手在安装包的`dex`文件中搜索`properties.json`，将然后搜索出来的
> > > `https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json`
> > > 改成自己的仓库文件地址就好
> > > `https://raw.githubusercontent.com/你的git用户名/你的git仓库/分支/文件名`
> > > 无码源目测可以在`https://tellme.pw/avsox`这个地址中找
> > > 有码源目测可以在`https://tellme.pw/avmoo`这个地址中找
> > > 附赠一份配置文件，我配置好了两个源的新地址可供参考使用
> > > ```
> > > {
> > >   "latest_version": "2.0.0 Alpha 1",
> > >   "latest_version_code": "13",
> > >   "changelog": "**测试版更新**\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题",
> > >   "data_sources": [
> > >     {
> > >       "name": "AVMOO 日本",
> > >       "link": "https://avmoo.xyz",
> > >       "legacies":[
> > >         "avmoo.net",
> > >         "avmoo.pw",
> > >         "javmoo.com",
> > >         "javlog.com",
> > >         "javtag.com",
> > >         "javhip.com",
> > >         "avos.pw",
> > >         "avmo.pw",
> > >         "avmo.club",
> > >         "avio.pw",
> > >         "javdog.com",
> > >         "javmoo.net"
> > >       ]
> > >     },
> > >     {
> > >       "name": "AVMOO 日本无码",
> > >       "link": "https://avsox.net",
> > >       "legacies":[
> > >         "javkey.com",
> > >         "javfee.com",
> > >         "javpee.com",
> > >         "avso.pw",
> > >         "avso.club"
> > >       ]
> > >     }
> > >   ]
> > > }
> > > ```
> > 
> > 
> > 大佬是直接在手机文件里面搜索吗
> > 直接在apk里面的dex里面搜索啊（推荐使用mt2管理器）
> > 把这个是我改好了的，下载解压，卸载原版安装即可
> > [app-release(2)_sign.zip](https://github.com/SplashCodes/JAViewer/files/3124930/app-release.2._sign.zip)

哇谢谢大佬

**Comment by lwq553238966** [comment]
> > > 作者在软件中使用的源更新方式是请求这个混帐的仓库`properties.json`文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
> > > 可以自己动手在安装包的`dex`文件中搜索`properties.json`，将然后搜索出来的
> > > `https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json`
> > > 改成自己的仓库文件地址就好
> > > `https://raw.githubusercontent.com/你的git用户名/你的git仓库/分支/文件名`
> > > 无码源目测可以在`https://tellme.pw/avsox`这个地址中找
> > > 有码源目测可以在`https://tellme.pw/avmoo`这个地址中找
> > > 附赠一份配置文件，我配置好了两个源的新地址可供参考使用
> > > ```
> > > {
> > >   "latest_version": "2.0.0 Alpha 1",
> > >   "latest_version_code": "13",
> > >   "changelog": "**测试版更新**\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题",
> > >   "data_sources": [
> > >     {
> > >       "name": "AVMOO 日本",
> > >       "link": "https://avmoo.xyz",
> > >       "legacies":[
> > >         "avmoo.net",
> > >         "avmoo.pw",
> > >         "javmoo.com",
> > >         "javlog.com",
> > >         "javtag.com",
> > >         "javhip.com",
> > >         "avos.pw",
> > >         "avmo.pw",
> > >         "avmo.club",
> > >         "avio.pw",
> > >         "javdog.com",
> > >         "javmoo.net"
> > >       ]
> > >     },
> > >     {
> > >       "name": "AVMOO 日本无码",
> > >       "link": "https://avsox.net",
> > >       "legacies":[
> > >         "javkey.com",
> > >         "javfee.com",
> > >         "javpee.com",
> > >         "avso.pw",
> > >         "avso.club"
> > >       ]
> > >     }
> > >   ]
> > > }
> > > ```
> > 
> > 
> > 大佬是直接在手机文件里面搜索吗
> > 直接在apk里面的dex里面搜索啊（推荐使用mt2管理器）
> > 把这个是我改好了的，下载解压，卸载原版安装即可
> > [app-release(2)_sign.zip](https://github.com/SplashCodes/JAViewer/files/3124930/app-release.2._sign.zip)

大佬下不动啊，太慢了，下载失败

**Comment by wunai1234** [comment]
> > > > 作者在软件中使用的源更新方式是请求这个混帐的仓库`properties.json`文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
> > > > 可以自己动手在安装包的`dex`文件中搜索`properties.json`，将然后搜索出来的
> > > > `https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json`
> > > > 改成自己的仓库文件地址就好
> > > > `https://raw.githubusercontent.com/你的git用户名/你的git仓库/分支/文件名`
> > > > 无码源目测可以在`https://tellme.pw/avsox`这个地址中找
> > > > 有码源目测可以在`https://tellme.pw/avmoo`这个地址中找
> > > > 附赠一份配置文件，我配置好了两个源的新地址可供参考使用
> > > > ```
> > > > {
> > > >   "latest_version": "2.0.0 Alpha 1",
> > > >   "latest_version_code": "13",
> > > >   "changelog": "**测试版更新**\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题",
> > > >   "data_sources": [
> > > >     {
> > > >       "name": "AVMOO 日本",
> > > >       "link": "https://avmoo.xyz",
> > > >       "legacies":[
> > > >         "avmoo.net",
> > > >         "avmoo.pw",
> > > >         "javmoo.com",
> > > >         "javlog.com",
> > > >         "javtag.com",
> > > >         "javhip.com",
> > > >         "avos.pw",
> > > >         "avmo.pw",
> > > >         "avmo.club",
> > > >         "avio.pw",
> > > >         "javdog.com",
> > > >         "javmoo.net"
> > > >       ]
> > > >     },
> > > >     {
> > > >       "name": "AVMOO 日本无码",
> > > >       "link": "https://avsox.net",
> > > >       "legacies":[
> > > >         "javkey.com",
> > > >         "javfee.com",
> > > >         "javpee.com",
> > > >         "avso.pw",
> > > >         "avso.club"
> > > >       ]
> > > >     }
> > > >   ]
> > > > }
> > > > ```
> > > 
> > > 
> > > 大佬是直接在手机文件里面搜索吗
> > > 直接在apk里面的dex里面搜索啊（推荐使用mt2管理器）
> > > 把这个是我改好了的，下载解压，卸载原版安装即可
> > > [app-release(2)_sign.zip](https://github.com/SplashCodes/JAViewer/files/3124930/app-release.2._sign.zip)
> 
> 大佬下不动啊，太慢了，下载失败

用uc下

**Comment by Arturia2019** [comment]
可用，谢谢

**Comment by ying0303** [comment]
我下载了那个怎么还是空白呢-_-||

**Comment by liricheng** [comment]
同 安卓用户还是空白

**Comment by fengberd** [comment]
@ShmilyChen  亲这边建议您直接开PR改主仓库的链接哦

> 作者在软件中使用的源更新方式是请求这个git仓库的`properties.json`文件，这也是每次切换源都需要重新在本地文件设置的原因，所有我们只需要把这个请求地址改成我们已经配置好的地址可以了
> 可以自己动手在安装包的`dex`文件中搜索`properties.json`，然后将搜索出来的
> `https://raw.githubusercontent.com/SplashCodes/JAViewer/master/properties.json`
> 改成自己的仓库文件地址就好
> `https://raw.githubusercontent.com/你的git用户名/你的git仓库/分支/文件名`
> 无码源目测可以在`https://tellme.pw/avsox`这个地址中找
> 有码源目测可以在`https://tellme.pw/avmoo`这个地址中找
> 附赠一份配置文件，我配置好了两个源的新地址可供参考使用
> 
> ```
> {
>   "latest_version": "2.0.0 Alpha 1",
>   "latest_version_code": "13",
>   "changelog": "**测试版更新**\n2.0.0 alpha 1 \n1. 在线播放功能重磅来袭\n2. 部分界面重置\n3. 全新侧边菜单，Material Design 2.0风格\n4.修复已知问题\n\n该版本为测试版，欢迎大家反馈问题",
>   "data_sources": [
>     {
>       "name": "AVMOO 日本",
>       "link": "https://javzoo.com",
>       "legacies":[
>         "avmoo.net",
>         "avmoo.pw",
>         "javmoo.com",
>         "javlog.com",
>         "javtag.com",
>         "javhip.com",
>         "avos.pw",
>         "avmo.pw",
>         "avmo.club",
>         "avio.pw",
>         "javdog.com",
>         "javmoo.net"
>       ]
>     },
>     {
>       "name": "AVMOO 日本无码",
>       "link": "https://avme.pw",
>       "legacies":[
>         "javkey.com",
>         "javfee.com",
>         "javpee.com",
>         "avso.pw",
>         "avso.club"
>       ]
>     }
>   ]
> }
> ```

@ShmilyChen 亲亲这边建议您直接开PR改主仓库里的配置文件哦，这样就是设计成在线配置的初衷呢。如果亲还有更多问题请继续开PR自己修哦

**Comment by ShmilyChen** [comment]
> 亲亲这边建议您直接开PR改主仓库里的配置文件哦，这样就是设计成在线配置的初衷呢。如果亲还有更多问题请继续开PR自己修哦

有人直接拿去提就是啊，我不太想那这个号去提（这个号比较个人）

**Comment by yybrave** [comment]
搞定
https://github.com/SplashCodes/JAViewer/issues/254#issuecomment-487396989

**Comment by lj98lj98** [comment]
感谢以上热心大佬提供分享，也期待官方更新alpha2

**Comment by tkswfghk** [comment]
[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/)

[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/)

[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/)   
    
凳车伟挠托撼啬凉涟勤压字巡侍偾颗蓉浅坝杀瓤勇部撼缎假牟址

**Comment by jjawgj** [comment]
[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/?ss)

[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/?ss)

[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/?ss)   
    
柯访透沤苏至啃肺四窒厍臀吵荒短
