### ISSUE TITLE
域名变了，请更新

### ISSUE THREAD

**Issue by CoderYellow** [SplashCodes/JAViewer#267]
[这些地址](https://github.com/SplashCodes/JAViewer/blob/9997703835c382eaab76c22da750943d56808287/properties.json#L5)会被重定向到地址发布页，目前新地址是这两个
```
https://avmoo.asia
https://avmoo.com
```

**Comment by qiudaoyudesu** [comment]
不知道app上怎么改...

**Comment by HiverWei** [comment]
同求，怎么更新，前几天还能用

**Comment by a23723629178049** [comment]
怎么改

**Comment by ddddnb** [comment]
更新配置文件可以解决，我分享在官方群了

**Comment by HiverWei** [comment]
群呢？

**Comment by Yukino650** [comment]
群怎么进

**Comment by tjtjyys41** [comment]
用es文件浏览器，找到javiewer文件夹，然后修改里面的文件，link那里

**Comment by Yukino650** [comment]
javiewer 文件夹里只有一个文件吧，我刚刚看了下

**Comment by Yukino650** [comment]
我这没有link文件哈哈哈
可以直接创一个link文件夹嘛

**Comment by Ecolinnn** [comment]
直接改json文件里的开头的位置，link后面的网址的.xyz改成com就好了
但是原来收藏的番点进去就出错了，重新搜番号取消收藏再重新收藏就好了，应该也是链接有问题吧

**Comment by Yukino650** [comment]
试了，没用啊。我还把收藏全删了，把上面的代码复制过去，没用

**Comment by Yukino650** [comment]
...别沉啊这楼

**Comment by a23723629178049** [comment]
我猜那个手机上的json只是我们收藏的缓存吧  改了也没用

**Comment by Yukino650** [comment]
确实是，我改了后缓存没有了

**Comment by Yukino650** [comment]
所以怎么办啊，哭😭

**Comment by john9095** [comment]
安卓下个json精灵编辑器就能改

**Comment by 320070993** [comment]
谁拉我进下群。感谢

**Comment by ZXCASD854** [comment]
含羞草实验研究所永久地址 [618sss.com](http://618sss.com)

**Comment by tkswfghk** [comment]
[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/)

[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/)

[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/)   
    
祷问即荡撇钡锰灸嗽非巫刃丛瘫识仄倥亟只回撞怪

**Comment by jjawgj** [comment]
[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/?ss)

[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/?ss)

[>>>>>让男人爽的视频,你懂的](https://dfghjke.com/?ss)   
    
凹炙灾孔家阜匕榷胁背咕怪装弥窃录盐亲脸褂账位咆税凸茨
