### ISSUE TITLE
1.2.2某些类别卡死

### ISSUE THREAD

**Issue by 1357209470** [SplashCodes/JAViewer#27]
按类别选 乱伦 到2016年7月10几号开始往后的 点击进去不显示 空白一片一直在转圈 软件卡死操作无反应 其他类别未发现这个情况
 安卓系统7.1.1
还请管理员修复 谢谢

**Comment by SplashCodes** [comment]
请提供番号

**Comment by 1357209470** [comment]
就是 16年7月10集号开始  无法精确具体番号 只有1.2.2版本 在安卓7.1.1上有这个问题 1.2没问题 安卓6.0上也没出现这个问题 其他类别也没有出现这个问题
我回复邮件也不知道你能不能收到。 不太会弄哈

**Comment by 1357209470** [comment]
不是个别番号的问题啊，按乱lUN类别查看到16年7月10几号就看不了了

**Comment by SplashCodes** [comment]
请提供出问题的一个番号我才能调试

**Comment by 1357209470** [comment]
hetR-003
