### ISSUE TITLE
更新配置文件的具体方法

### ISSUE THREAD

**Issue by ddddnb** [SplashCodes/JAViewer#273]
官方群新来的朋友看不到历史文件，为避免重复说明现把方法分享在此处。
手机内部存储中JAViewer文件夹下有个配置文件configurations.json，通过文本方式打开此文件，把文件中所有javzoo.com修改为avmoo.asia，保存后挂梯子可正常使用绝大部分功能。目前已知问题：不能切换无码源。

**Comment by lj98lj98** [comment]
配置文件是缓存，这样改能长久吗？作者好似不维护了。

**Comment by xpilove2008** [comment]
请问怎么上官方的车？？

**Comment by zql5627710** [comment]
我就想问问还有没有其他能用的

**Comment by huthkj** [comment]
请问怎么上官方群呢

**Comment by wuwangaoao** [comment]
官方群是啥？？？
