### ISSUE TITLE
求助大佬推荐几个能用的梯子！

### ISSUE THREAD

**Issue by Forcefulq** [SplashCodes/JAViewer#274]
感谢

**Comment by xujingj** [comment]
nodevpn

**Comment by somsonsun** [comment]
我在用旋风加速器
每天能免费用两个小时
https://www.fj66.live/redirect?code=9WGJE4E

**Comment by grainrain** [comment]
自己弄个搬瓦工服务器，搭VPS

**Comment by ye40** [comment]
现在帮瓦工性价比太低不走屌丝路线了不推荐，hostdare、virmach都挺不错，关键是可用ip都不多
