### ISSUE TITLE
bt下载链接空白不显示怎么解决？

### ISSUE THREAD

**Issue by shamegod11** [SplashCodes/JAViewer#280]
求解

**Comment by tailuocao** [comment]
+1

**Comment by ruoxuehuimou** [comment]
+1( ‘-ωก̀ )

**Comment by ruoxuehuimou** [comment]
啥也不懂就只能期待大佬的解决方案了( ๑ŏ ﹏ ŏ๑ )

**Comment by bjzp876** [comment]
+1

**Comment by j919936900** [comment]
现在还是不能下载么？

**Comment by bjzp876** [comment]
是的



---原始邮件---
发件人: "j919936900"<notifications@github.com>
发送时间: 2019年8月8日(星期四) 中午11:52
收件人: "SplashCodes/JAViewer"<JAViewer@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"bjzp876"<2680550908@qq.com>;
主题: Re: [SplashCodes/JAViewer] bt下载链接空白不显示怎么解决？ (#280)



现在还是不能下载么？

**Comment by j919936900** [comment]
> 是的
> [...](#)
> ---原始邮件--- 发件人: "j919936900"<notifications@github.com> 发送时间: 2019年8月8日(星期四) 中午11:52 收件人: "SplashCodes/JAViewer"<JAViewer@noreply.github.com>; 抄送: "Comment"<comment@noreply.github.com>;"bjzp876"<2680550908@qq.com>; 主题: Re: [SplashCodes/JAViewer] bt下载链接空白不显示怎么解决？ (#280) 现在还是不能下载么？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

有没有什么其他的解决办法

**Comment by j919936900** [comment]
有没有什么其他的解决办法


------------------ 原始邮件 ------------------
发件人: "bjzp876"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 中午11:59
收件人: "SplashCodes/JAViewer"<JAViewer@noreply.github.com>;
抄送: "(7A13N10) 活动中心"<919936900@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [SplashCodes/JAViewer] bt下载链接空白不显示怎么解决？ (#280)



是的 
 
 
 
 ---原始邮件--- 
 发件人: "j919936900"<notifications@github.com> 
 发送时间: 2019年8月8日(星期四) 中午11:52 
 收件人: "SplashCodes/JAViewer"<JAViewer@noreply.github.com>; 
 抄送: "Comment"<comment@noreply.github.com>;"bjzp876"<2680550908@qq.com>; 
 主题: Re: [SplashCodes/JAViewer] bt下载链接空白不显示怎么解决？ (#280) 
 
 
 
 现在还是不能下载么？

**Comment by j919936900** [comment]
兄弟，有车么
------------------ 原始邮件 ------------------
发件人: "bjzp876"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 中午11:59
收件人: "SplashCodes/JAViewer"<JAViewer@noreply.github.com>;
抄送: "(7A13N10) 活动中心"<919936900@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [SplashCodes/JAViewer] bt下载链接空白不显示怎么解决？ (#280)



是的 
 
 
 
 ---原始邮件--- 
 发件人: "j919936900"<notifications@github.com> 
 发送时间: 2019年8月8日(星期四) 中午11:52 
 收件人: "SplashCodes/JAViewer"<JAViewer@noreply.github.com>; 
 抄送: "Comment"<comment@noreply.github.com>;"bjzp876"<2680550908@qq.com>; 
 主题: Re: [SplashCodes/JAViewer] bt下载链接空白不显示怎么解决？ (#280) 
 
 
 
 现在还是不能下载么？

**Comment by qq2439343568** [comment]
加我qq 2439343568  帮你解决  福利哦
