### ISSUE TITLE
配置文件修改

### ISSUE THREAD

**Issue by yuepeng666** [SplashCodes/JAViewer#281]
找到JAViewer文件夹修改configurations.json文件，如果没有该文件新建一个即可，代码如下{"data_source":{"legacies":["avmoo.asia","avmoo.net","avmoo.pw","javmoo.com","javlog.com","javtag.com","javhip.com","avos.pw","avmo.pw","avmo.club","avio.pw","javdog.com","javmoo.net","avmoo.asia"],"name":"AVMOO 日本","link":"https://avmoo.asia"},"download_counter":0,"show_ads":false,"starred_actresses":[],"starred_movies":[]}

**Comment by 17764143746** [comment]
新建不了啊，文件中不能包涵特殊字符

**Comment by nmyo** [comment]
这样弄没法搜索链接啊

**Comment by 17764143746** [comment]
我这还是空白

**Comment by nmyo** [comment]
你用es创一个文本，名字改成和这个一样的，内容复制一下

**Comment by magicaaaa** [comment]
改了浏览是可以，但是下载链接是空的
