### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by gtaxxs** [SplashCodes/JAViewer#282]
欧美也换了
avmemo.asia
btso的新域名
btspread.com
原来btso的域名就换成btsow了

**Comment by tailuocao** [comment]
什么意思啊  大佬教教我

**Comment by yimoudo** [comment]
原文件没有btso咋办

**Comment by 614590692** [comment]
下载页面  空白   加载不出来怎么办？

**Comment by Bravo16** [comment]
哪里有欧美啊？2.0版本只有无码和有码两种啊，另外我想问下大佬为什么我收藏夹中以前的片点进去后就一直加载不出来了呢？刚保存的却可以？
