### ISSUE TITLE
收藏夹。网站后缀地址换了，那个大神开发下替换地址软件

### ISSUE THREAD

**Issue by bobcatss** [SplashCodes/JAViewer#285]
手动替换很麻烦

读取配置文件，批量替换链接的软件谁能写个！
演员板块，抓取姓名去网站找链接替换链接！
影片板块，抓取车牌去网站找链接替换链接！

**Comment by 980864138** [comment]
并不只是域名换了，url全变了，还是自己手动重新收藏吧

**Comment by passpos** [comment]
不必替换所有链接，只需找到"data_source"下的“link”键，将这个键的键值替换成"https://avmoo.asia"，即可。

**Comment by bobcatss** [comment]
![QQ截图20190724221604](https://user-images.githubusercontent.com/39665030/61801093-c6634a00-ae60-11e9-8183-5714c3dc2a33.jpg)
这个地址。重新收藏太麻烦了。收藏了50多个和一些影片。

**Comment by lanlan1234** [comment]
那个大神来帮个忙丫
