### ISSUE TITLE
下载不了求解决  奉上100元红包  万分感谢

### ISSUE THREAD

**Issue by 614590692** [SplashCodes/JAViewer#292]
点击下载页面空白   求解决办法

**Comment by litai1415457996** [comment]
加我的qq 1415457996 我给你发

**Comment by kilo-swodh** [comment]
https://github.com/SplashCodes/JAViewer/issues/294#issue-483178762

**Comment by qinkk156** [comment]
下载问题，我有新的Btso网址然后有配套的在线播放软件，下载软件可以给你😄，加我2466078603，这里发不了
