### ISSUE TITLE
居然还有人秀下限收费下载?要APK的进

### ISSUE THREAD

**Issue by kilo-swodh** [SplashCodes/JAViewer#294]
实在看不下去了,用最新版代码自己打了个包
去掉了更新提示,升了下api
下载地址: https://www.lanzous.com/b923611/ 
密码:bjcd

**Comment by qq2439343568** [comment]
下载页面空白的帮你解决 qq2439343568

**Comment by magicaaaa** [comment]
下载页面还是空白

**Comment by kilo-swodh** [comment]
> 下载页面还是空白

科学上网

**Comment by magicaaaa** [comment]
科学上网也没用

**Comment by kilo-swodh** [comment]
> 科学上网也没用

我这边在不同的网络下测试,有时候可以直连,如果直连不上就科学上网就能用

**Comment by MotootE** [comment]
em不知道为啥，点击安卓直接就显示应用程序未安装。以前的文件都删光了。

**Comment by Telk123** [comment]
想问一下，你打包的指纹版路径还是和之前版本路径一样吗？我卸载掉以前的，再安装你的，收藏夹的都没了，但是我有备份，所以请问一下，路径在哪？

**Comment by kilo-swodh** [comment]
> 想问一下，你打包的指纹版路径还是和之前版本路径一样吗？我卸载掉以前的，再安装你的，收藏夹的都没了，但是我有备份，所以请问一下，路径在哪？

指纹版只是在启动时加了个验证,包名和内部代码上没做任何修改,只是签名会不一样了
具体实现没看,大概是存在configurations.json这个文件里了

**Comment by Telk123** [comment]
好的，谢谢！
