### ISSUE TITLE
请问app是停止维护了么？

### ISSUE THREAD

**Issue by ZerOri** [SplashCodes/JAViewer#297]
太可惜了，很不错的app的说……

**Comment by WaiHou** [comment]
一直想要一个ios的

**Comment by jzy131419** [comment]
1、精彩爱情动作片 无需翻墙 流畅观看 ！ 
 
2、下载即可观看，无需注册，兼容iOS、Android  

3、最新片源、与日本同步更新！ 

4、最新门事件，主播、各路国产大神片源！更有漫画、小说等你来看 

BOBO推荐：3D肉蒲团上架了、海量三级片等你来看，猛戳下载链接↓↓↓即可欣赏 
 （如果链接打不开请复制到浏览器中打开） 
https://s.jjjjgggssss24.com/gw/app-config/cds/pushPeople/1?code=ARZP4C6GE
