### ISSUE TITLE
我看在线视频，一直显示视频加载失败是为什么

### ISSUE THREAD

**Issue by loggedyear** [SplashCodes/JAViewer#298]
有人能帮忙解答一下吗

**Comment by over-driver** [comment]
这里面使用的获取Avgle的api好像暂时失效了，目前可以使用webview直接播放嵌入视频[https://github.com/over-driver/SevenTV](https://github.com/over-driver/SevenTV)

**Comment by wtxjjjn** [comment]
怎么用seventv播放嵌入视频啊？怎么操作啊

**Comment by over-driver** [comment]
在详情页内点击播放就可以了，需要翻墙
