### ISSUE TITLE
问下本地收藏能不能导出

### ISSUE THREAD

**Issue by Yumkamii** [SplashCodes/JAViewer#30]
如果换手机了什么的还是希望数据能保留下来 ~~

**Comment by SplashCodes** [comment]
Sd卡下的javiewer目录就是，我可能会考虑加个导出功能 :)

**Comment by Yumkamii** [comment]
O(∩_∩)O好的

**Comment by SplashCodes** [comment]
https://github.com/SplashCodes/JAViewer/issues/40
