### ISSUE TITLE
要修改版的直接进来下载，发群里效率太差一直有人问

### ISSUE THREAD

**Issue by SeanChengN** [SplashCodes/JAViewer#302]
https://github.com/SeanChengN/JAViewer/releases/tag/2.0.0-Fuck

**Comment by candy731** [comment]
你好，请问在哪里可以下载app

**Comment by candy731** [comment]
在哪里可以下载

**Comment by SeanChengN** [comment]
> 在哪里可以下载

我不是发了吗😂

**Comment by hdbcjr** [comment]
为什么我打开是空白页，加载不出来，是不是改域名了

**Comment by visionoffuture** [comment]
视频加载失败怎么办

**Comment by SeanChengN** [comment]
> 为什么我打开是空白页，加载不出来，是不是改域名了

切换一下无码再切回来，再不行挂梯子

**Comment by SeanChengN** [comment]
> 视频加载失败怎么办

无解

**Comment by visionoffuture** [comment]
> > 视频加载失败怎么办
> 
> 无解

谢谢回复！那这样这个app是不是就没用了？

**Comment by SeanChengN** [comment]
> > > 视频加载失败怎么办
> > 
> > 
> > 无解
> 
> 谢谢回复！那这样这个app是不是就没用了？

当收藏夹用，或者用[SevenTV](https://github.com/over-driver/SevenTV)

**Comment by visionoffuture** [comment]
> > > > 视频加载失败怎么办
> > > 
> > > 
> > > 无解
> > 
> > 
> > 谢谢回复！那这样这个app是不是就没用了？
> 
> 当收藏夹用，或者用[SevenTV](https://github.com/over-driver/SevenTV)

谢谢！

**Comment by mond1996** [comment]
有码的加载不出啊～～

**Comment by yjr815jun** [comment]
大佬厉害！

**Comment by huihuiusys** [comment]
有码的显示是空白页，其他都正常

**Comment by hdbcjr** [comment]
其他正常。有码的看不了，估计域名换了

**Comment by SeanChengN** [comment]
@hdbcjr @huihuiusys @mond1996 
有码白屏的解决办法我已经发过几遍了，自行查看：
- 切换一下无码再切回来，自动更新网址。
- 搭梯子/换线路，由于最近国庆墙高了，有码的网站被墙。

**Comment by flys9527** [comment]
apk一直下载失败，怎么搞

**Comment by gxjz520** [comment]
多想多谢

**Comment by yjr815jun** [comment]
大佬...之前用的没问题...没白屏内容都正常非常好～昨天我刷机出问题...重装系统后...直接装你的这个无法保存收藏了（可以保存但是退出之后再打开什么都没有）权限也给了...把之前的收藏C开头的json文件复制回路径也没用～还收藏夹还是空白～请问大佬怎么办？

**Comment by bsg1996** [comment]
谢谢

**Comment by KareizawaKei** [comment]
谢谢老哥

**Comment by Domoya** [comment]
下不动是啥情况
