### ISSUE TITLE
有码域名又变了，请更新

### ISSUE THREAD

**Issue by CoderYellow** [SplashCodes/JAViewer#305]
已变更为
https://avmask.com/

**Comment by qq1301922577** [comment]
怎么更新啊，能教教我吗

**Comment by qq1301922577** [comment]
我忘记怎么改了

**Comment by drduan** [comment]
<img width="1125" alt="截屏2019-10-1320 47 27" src="https://user-images.githubusercontent.com/7875572/66715847-bb360f80-edfa-11e9-96e8-47211162181a.png">

这样就没办法了 timeout 410 @CoderYellow
