### ISSUE TITLE
请大佬们提供一个资源

### ISSUE THREAD

**Issue by achao12345** [SplashCodes/JAViewer#319]
我原来的资源不小心删掉了，重新下载的资源打不开，请大佬们提供一下资源，谢谢啦

**Comment by gunfuzi123** [comment]
新版本怎么下载

**Comment by achao12345** [comment]
> 版

就在这上面下载的那个2.0版本的，现在打不开呀

**Comment by gunfuzi123** [comment]
谢谢，下好了，但是进去之后点开视频在线播放，显示暂无视频源，是什么意思



---原始邮件---
发件人: "achao12345"<notifications@github.com&gt;
发送时间: 2020年2月17日(周一) 晚上11:36
收件人: "SplashCodes/JAViewer"<JAViewer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"gunfuzi123"<1311570907@qq.com&gt;;
主题: Re: [SplashCodes/JAViewer] 请大佬们提供一个资源 (#319)


 
版
  
就在这上面下载的那个2.0版本的，现在打不开呀

**Comment by achao12345** [comment]
> 谢谢，下好了，但是进去之后点开视频在线播放，显示暂无视频源，是什么意思
> […](#)
> ---原始邮件---发件人：“ achao12345” <notifications@github.com> 发送时间：2020年2月17日（周一）晚上11:36收件人：“ SplashCodes / JAViewer” <JAViewer@noreply.github.com> ;; 抄送：“ Comment” <comment@noreply.github.com> ;;“ gunfuzi123” <1311570907@qq.com> ;; 主题：回复：[SplashCodes / JAViewer]请大佬们提供一个资源（[＃319](https://github.com/SplashCodes/JAViewer/issues/319)）版本就在这上面下载的那个2.0版本的，现在打不开呀 直接回复此电子邮件，在GitHub上查看或取消订阅。

**Comment by achao12345** [comment]
> 谢谢，下好了，但是进去之后点开视频在线播放，显示暂无视频源，是什么意思
> […](#)
> ---原始邮件---发件人：“ achao12345” <notifications@github.com> 发送时间：2020年2月17日（周一）晚上11:36收件人：“ SplashCodes / JAViewer” <JAViewer@noreply.github.com> ;; 抄送：“ Comment” <comment@noreply.github.com> ;;“ gunfuzi123” <1311570907@qq.com> ;; 主题：回复：[SplashCodes / JAViewer]请大佬们提供一个资源（[＃319](https://github.com/SplashCodes/JAViewer/issues/319)）版本就在这上面下载的那个2.0版本的，现在打不开呀 直接回复此电子邮件，在GitHub上查看或取消订阅。

可以探讨一下，能不能加您一下QQ

**Comment by uheejkd** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
惫闪票倭屑
