### ISSUE TITLE
可否把文件上传到国内云盘？

### ISSUE THREAD

**Issue by AxlXNick** [SplashCodes/JAViewer#42]
github的链接实在是太慢，会员下载也跑不动，同时软件提示我更新可是下载下不完，下到一半就断了。
要是能上传到百度云之类的网盘，下载速度就有保证了。

**Comment by gjhjjfgjg** [comment]
使用磁力播放器，旗鱼影音(酷安有)即可在线看
非要下载的话先将种子洗白再迅雷下或百度云离线(安装脚本: https://greasyfork.org/scripts/22590-%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD/code/%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD.user.js
用谷歌浏览器打开，要安装油猴插件  作用，离线主流链接到百度云)

**Comment by SplashCodes** [comment]
;) 下次发布时可能会考虑
主要是不喜百度，限速，可靠性也不能保证分分钟失效

**Comment by Vstory** [comment]
可以尝试下的 [腾讯微云](https://www.weiyun.com) 网盘，下载还行。

**Comment by gjhjjfgjg** [comment]
压缩上传不易gg
