### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by gjhjjfgjg** [SplashCodes/JAViewer#43]
可以添加里番与本子么

数据源可以甪琉璃神社，寂月神社，E站，国外的bt放流站，百度云的分享链接，及各种论坛，
还有发现一个bug:
应用运行中按home键/多窗口键切换到卓面/其它应用后，再打开本应用会白屏/停止运行，要清除数据才可以打开

希望增加
磁力解析，可以解析出压缩包里的视频并支持带密码的压缩包，然后将选中的视频比对库中是否有资源，有资源显示磁力链接，没有资源服务器将做种或离线到百度云盘(油猴有不用客户端就可以将主流链接离线的脚本)并给出视频api接口的链接或晋通的分享链接，api链接复制到qq浏览器可以直接打开播放
用户体系
用户可以上传并更新资源(链接与图片预览及简介等信息)到库
用户可以用虚拟积分(含税[即悬赏积分+x值])发布悬赏到展示板，用户可以接悬赏后完成获取积分
设置增加清除缓存功能
自定义主题色
更多的磁力搜索引擎

**Comment by SplashCodes** [comment]
`数据源可以甪琉璃神社，寂月神社，E站，国外的bt放流站，百度云的分享链接，及各种论坛，`
复杂度太高无此开发计划
`应用运行中按home键/多窗口键切换到卓面/其它应用后，再打开本应用会白屏/停止运行，要清除数据才可以打开`
未遇到此问题请检查有无限制后台的程序
`磁力解析，可以解析出压缩包里的视频并支持带密码的压缩包，然后将选中的视频比对库中是否有资源，有资源显示磁力链接，没有资源服务器将做种或离线到百度云盘(油猴有不用客户端就可以将主流链接离线的脚本)并给出视频api接口的链接或晋通的分享链接，api链接复制到qq浏览器可以直接打开播放`
过于复杂，有风险，不便于维护
`用户体系
用户可以上传并更新资源(链接与图片预览及简介等信息)到库
用户可以用虚拟积分(含税[即悬赏积分+x值])发布悬赏到展示板，用户可以接悬赏后完成获取积分`
本软件使用第三方数据源，无法实现
`设置增加清除缓存功能`
设置中可以清除，缓存由glide自动管理一般不需要清除
`自定义主题色
更多的磁力搜索引擎`
可行。

**Comment by SplashCodes** [comment]
https://github.com/SplashCodes/JAViewer/issues/40
