### ISSUE TITLE
1.3发现的问题

### ISSUE THREAD

**Issue by KyleThanas** [SplashCodes/JAViewer#49]
手机：oppo r9
问题：1.添加收藏软件卡住，需要杀掉重新打开，添加收藏成功，1.2.2没问题
2.没有标签
3.女优排序头像过小，体验不如之前的1.2.2版式
希望追加：好评系统

**Comment by 1357209470** [comment]
女优排列方面我到觉得挺好的，大小都是看头像而已，现在的排列比1.2更美观方便，（个人习惯）
.一加一未发现收藏卡着的bug
感谢作者大大的更新 谢谢

**Comment by KyleThanas** [comment]
font{
        line-height: 1.5;
    }


    

讲道理 oppo点击收藏真的卡，每次点击后页面不动，杀掉重开，早上我又去重新下载了1.2.2感谢作者大大


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    




    在2017年05月5日 14:03，1357209470<notifications@github.com> 写道： 


女优排列方面我到觉得挺好的，大小都是看头像而已，现在的排列比1.2更美观方便，（个人习惯）
.一加一未发现收藏卡着的bug
感谢作者大大的更新 谢谢

**Comment by 1357209470** [comment]
嗯嗯 我只是说一下我的机型未发现问题，1.2.2版本我的机型有发现问题1.3并未发现。 。没有针对楼主的意思，不太会说话见谅啊
女优排列方面习惯不一样吧，希望作者大大可以增加更多的排列方式吧 

感谢作者大大的付出

**Comment by 1357209470** [comment]
同发现添加收藏卡死问题。

**Comment by iwenbin** [comment]
索尼Z2 Android 5.1.1也遇到收藏卡死的现象，但感觉这版响应快了，望解决

**Comment by Climamba** [comment]
我刚更新没有 现在有收藏卡住的问题了

**Comment by SplashCodes** [comment]
请试试1.3.1如无问题请关闭本issue

**Comment by luo945** [comment]
JAViewer1.3.1一点收藏按钮就无响应！
