### ISSUE TITLE
Error:Execution failed for task ':app:processDebugGoogleServices'. > File google-services.json is missing. The Google Services Plugin cannot function without it.     Searched Location:    /Users/sunchuanwen/Desktop/JAViewer/app/src/debug/google-services.json   /Users/sunchuanwen/Desktop/JAViewer/app/google-services.json

### ISSUE THREAD

**Issue by itwen** [SplashCodes/JAViewer#55]
Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/sunchuanwen/Desktop/JAViewer/app/src/debug/google-services.json
  /Users/sunchuanwen/Desktop/JAViewer/app/google-services.json

**Comment by SplashCodes** [comment]
打包请删除谷歌服务后再打包

**Comment by l1607100569** [comment]
有哪些谷歌服务啊  删了一个报一堆错  完全运行不起来啊

**Comment by l1607100569** [comment]
OK 已经运行起来 我要体验优质的驾车感了

**Comment by genjigjj** [comment]
具体怎么操作啊，我也遇到这个问题了？

**Comment by itwen** [comment]
把谷歌服务相关的东西注释掉就行了，就是一个上报crash用的

**Comment by genjigjj** [comment]
多谢，已经解决，膜拜大神中。。
