### ISSUE TITLE
收藏夹问题

### ISSUE THREAD

**Issue by AxlXNick** [SplashCodes/JAViewer#56]
辛辛苦苦收藏了很多女优和片，切换了一下源换成欧美的，发现欧美的进不去，自动变成日本的，关键是！我的收藏全没了。。。心疼。。希望作者大佬能尽快修复。。桑心。。我刚刚试了试。确定了，只要切换了源，收藏夹就都没了。女优和片都没有了。

**Comment by SplashCodes** [comment]
根据你的情况来看应该是SD卡出什么问题了，并非软件BUG
