### ISSUE TITLE
启动画面分辨率问题

### ISSUE THREAD

**Issue by SplashCodes** [SplashCodes/JAViewer#6]
最近有人反馈启动画面拉伸问题。
初步排除分辨率原因，模拟器从320P测试到2K皆无问题
可能为系统原因，目前MIUI4.4.4 CM12.1有复现
请您反馈您的系统具体信息，谢谢

**Comment by rcsupermanjob** [comment]
720p有拉伸#滑稽

**Comment by zpfsqzyl** [comment]
1080p被拉伸
https://ooo.0o0.ooo/2016/10/01/57ef7e98566dc.png

**Comment by SplashCodes** [comment]
方便的话请提供一下是什么系统（AOSP，MIUI之类）以及系统版本和手机型号，谢谢

**Comment by zpfsqzyl** [comment]
CM12.1 小米4 5.1.1
2016年10月1日 17:20，SplashCodes <notifications@github.com>写道：方便的话请提供一下是什么系统（AOSP，MIUI之类）以及系统版本和手机型号，谢谢

**Comment by laizony** [comment]
MIUI 8 6.9.29 有拉伸
ASUS Zenfone 5/CM 13.1 正常

**Comment by iOver01** [comment]
红米 note2 cm12 5.1.1 有拉伸

**Comment by SplashCodes** [comment]
目前貌似也就只有MIUI和CM12有这个问题？

**Comment by hcxhzth** [comment]
为什么有的手机不能切换数据源

**Comment by bookyue** [comment]
魅族metal，Flyme5.1.110Y
1080p有拉伸现象

**Comment by pinocchio2mx** [comment]
http://stackoverflow.com/questions/34831142/how-to-center-vector-drawable-in-layer-list-without-scaling这好像是 API 21/22 上的一个Bug ， 得把logo换成位图才行

**Comment by SplashCodes** [comment]
@pinocchio2mx 
#blamegoogle
位图的话没法控制对于分辨率的相对大小，尴尬。

**Comment by pinocchio2mx** [comment]
@SplashCodes 确实没有好的解决方法，要不在21 22上面，theme里就不要设置logo了，延迟到布局里加载

**Comment by zpfsqzyl** [comment]
升级CM14.1（7.1）之后，就没有拉伸了
