### ISSUE TITLE
能不能加入多标签搜索

### ISSUE THREAD

**Issue by hentaiacg** [SplashCodes/JAViewer#62]
能够使用多个标签进行搜索

**Comment by 1357209470** [comment]
这个支持不过要翻墙 http://18avbook.com/categorylist_censored.htm

**Comment by 1357209470** [comment]
楼主有支持多标签搜索的网站吗 共享一下哈

**Comment by CodeFarmer1995** [comment]
@1357209470  @SplashCodes[javlibrary]( http://www.j12lib.com/cn/)这个可以多标签，但好像可以登录。能不能分别搜索再本地交

**Comment by 1357209470** [comment]
@CodeFarmer1995 这个不够全只能搜索女优片商制造商的。不支持番号多多累别搜索啊。 比如选择类别是居然和出轨，那么就可以搜索到包涵这两个类别的番号。以前有一个网站是这样的后来改收费了，没过多久网站就挂了。

**Comment by cc1024** [comment]
abase.me可以多标签搜索

**Comment by CodeFarmer1995** [comment]
@1357209470 可以的，你仔细看进阶搜索，这个其实是爬dmm的

_Sent from my ZUK Z1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
