### ISSUE TITLE
 【严重bug】部分番号日期显示不了

### ISSUE THREAD

**Issue by fsy953643268** [SplashCodes/JAViewer#75]
比如snis还有一些别的片商，2017年5月16日以后的片子都没有日期，搜制作商这些新片子会被排到最后面翻也翻不到。请修复……如果源也可以更改一下排序规则按番号从大到小排

**Comment by Climamba** [comment]
+1 有些要不是我在别处看到有新片 我还以为这些女优引退了呢

**Comment by itabxt** [comment]
请告知 源站

**Comment by xjdndnddk** [comment]
网站多少啊

**Comment by gsons** [comment]
你们是真不知道还是假不知道，。我感觉这个数据抓取频率不高，数据不太同步。

**Comment by SplashCodes** [comment]
@gsons 源站问题，我也很无奈呀
