### ISSUE TITLE
希望增加如下功能

### ISSUE THREAD

**Issue by yezhiqi55** [SplashCodes/JAViewer#8]
希望增加在单个分类里搜索的功能，比如类别里的其中一类，我在里面能搜我想看的女优的那类作品
现在的搜索不论在什么位置都是一搜就是全部里面，很难找东西。（比如我想看苍老师的OL片，搜苍老师就只有苍老师所有的片，打开OL类里面就是所有演过OL的了，很不方便）
还有希望能够增加一个按时间顺序正序或者倒序的排列选择（比如我想看苍老师早期的片子，要一直拖下去，拖很久才拖到底，像小蕾这种几千部的手抖酸了）
最后一个可有可无，有的话更好，就是增加女友中文名识别

**Comment by yezhiqi55** [comment]
或者搜索功能高级点，我可以直接搜“苍老师 OL” 这样

**Comment by SplashCodes** [comment]
搜索功能不是我写出来的，网站本身自带的搜索功能，我也想加但是暂时没有什么办法。

**Comment by cc1024** [comment]
有的网站带高级搜索功能，比如javlibrary.com和abase.me，看看能否更换数据源来实现？
