### ISSUE TITLE
avmo域名更换

### ISSUE THREAD

**Issue by pannacea** [SplashCodes/JAViewer#81]
现在已经用不了啦，完全加载不出来

**Comment by jane35622** [comment]
资源站，移动似乎墙了。代理了可以上。

**Comment by pannacea** [comment]
弱鸡不知道挂什么代理能上，（虽然现在也不想装这个app就是想问问）

**Comment by Ccixyj** [comment]
@pannacea  可以使用 https://github.com/Ccixyj/JBusDriver

**Comment by itabxt** [comment]
域名已更换，将修复。
