### ISSUE TITLE
很尴尬

### ISSUE THREAD

**Issue by 2042460161** [SplashCodes/JAViewer#85]
对于你的软件这次bug 我有一句歌词送给你 又回到最初的起点............................

**Comment by SplashCodes** [comment]
@2042460161 请用现行规范汉语言文字简述你遇到的问题，谢谢

**Comment by hnuzhoulin** [comment]
现在github的门槛这么低吗？一点点软件开发的基本概念，bug反馈的基本要素都木有的人都可以在github上面这样回复一个开源免费的软件了。。。。。。。
