### ISSUE TITLE
老哥，加载不出来标签

### ISSUE THREAD

**Issue by BrontByte** [SplashCodes/JAViewer#95]
https://i.loli.net/2017/10/31/59f820ef21700.png

**Comment by BrontByte** [comment]
https://i.loli.net/2017/10/31/59f821fce92f1.png

**Comment by BrontByte** [comment]
https://i.loli.net/2017/10/31/59f8226c6caf3.png

**Comment by SplashCodes** [comment]
请提供影片识别码以供分析问题。
